### ISSUE TITLE
Add references

### ISSUE THREAD

**Issue by annefou** [DataRockMyWorld/DataRockMyWorld.github.io#2]
When we write information about weather and climate, it is recommended to add references (to show your site is trustworthy).

For instance, when you say that the average temperatures in March/April in Ghana are between 26 deg and 31 deg: do you have a reference e.g. where did you find this information? 

> Global data from [ECMWF](https://registry.opendata.aws/ecmwf-era5/), shows an average 
> air temperature of 36 degrees celsius for Ghana over the period of March, a hot month.

Is it what you get from the data you plotted or did you find this information from your reading ?
- when you get information from your plots/analysis, it is good to put your finding in the context of your analysis. Here we analyze 1 day and we found that the average temperature at 2 metres was on average 36 degrees celcius in Ghana.
- If you read it somewhere then it is nice to add the link/info about it.

**Comment by DataRockMyWorld** [comment]
Noted with thanks.
Issue #2 fixed
