### ISSUE TITLE
Montages

### ISSUE THREAD

**Issue by annefou** [DataRockMyWorld/DataRockMyWorld.github.io#4]
On the website, the montages are very tiny and we don't see much. 

So maybe these are not very relevant to show and it is better to select and show a few individual plots rather than montages. If you want to show many larger plots, maybe adding separate web pages where you display one by one all the different times would be better.  

What do you think?

**Comment by annefou** [comment]
Another possibility for your montage is to change the number of plots on each row. If you have only 2 plots per row.

**Comment by DataRockMyWorld** [comment]
I think I will create a separate link to have all my plots. 
Thus I will show only a few in the article.
Montage issue #4 fixed
